### ISSUE TITLE
Troubleshooting page: highlight availability of internal logs 

### ISSUE THREAD

**Issue by rarsan** [pivotal-cf/docs-splunk#5]
Based on user feedback, it should be pointed out toward the top of the document that internal logs are available. When nozzle is still being configured (with no events streaming yet to Splunk), this is the first place to start troubleshooting.

That includes:
* /var/vcap/packages/splunk/var/log/splunk/
* /var/vcap/sys/log/splunk-forwarder
* /var/vcap/sys/log/splunk-nozzle

**Comment by jncd** [comment]
Hi @rarsan 
Would you make a pull-request for the fix you want added here? (assuming it's still needed)
Thanks,
Jane
