### ISSUE TITLE
Nozzle Cpu (%) and Nozzle Mem Total (MB) column data switched?

### ISSUE THREAD

**Issue by labrown** [pivotal-cf/docs-splunk#9]
Looks like the CPU% and Mem Total columns are switched in this table.   560% CPU?

**Comment by jncd** [comment]
@labrown Thanks very much for spotting and reporting this.
@dtregonning Please would you make a PR to correct this error.
TIA, Jane

cc: @jknostman3

**Comment by dtregonning** [comment]
@labrown 
Thanks for opening the issue.
What was meant was that of the 8 CPUS on the test machine around 5.6 were being used on average. Same concept as attached:
https://superuser.com/questions/174660/why-is-the-cpu-usage-reported-by-top-in-linux-over-100

With that said we will make it easier to understand.

**Comment by labrown** [comment]
I get it, which means my PR switched the column titles and actually made things more confusing.  I assume your update to make it easier to understand will repair that as well?
